- id: dotnet-format-check
  name: dotnet format check
  description: Check that C# files are formatted with dotnet format
  entry: hooks/dotnet-format-check.sh
  language: script
  files: [c#]
  pass_filenames: true